### ISSUE TITLE
Default value of public key

### ISSUE THREAD

**Issue by hisem** [lexik/LexikPayboxBundle#30]
Hi,

Commit 152eade00c525e0c90ae63a193588fc9cb662db6 gives the public_key parameter a null value in Paybox/System/Base/Response.php 's verifySignature function. The default value set in the extension didn't work for me. I had to patch this by putting the default value back in the Configuration so my transactions would verify the signature correctly.

**Comment by Olineuve** [comment]
As explained in https://github.com/lexik/LexikPayboxBundle/pull/39 the "public_key" is directly set in the bundle's configuration. The tested and then added to the "lexik_paybox.parameters".
I also removed "lexik_paybox.public_key" that wasn't used.
