### ISSUE TITLE
A parameter to set preproduction mode

### ISSUE THREAD

**Issue by LouTerrailloune** [lexik/LexikPayboxBundle#35]
Setting the propuction/prepoduction environment with a parameter in the config should be great.
This will allow us to use test mode for dev environment and production mode in the prod environment.

**Comment by Olineuve** [comment]
Changed in v1.1.0, you now have a configuration key to specify if the payment is in production or in test mode.

// config.yml
lexik_paybox:
    parameters:
        production: true

**Comment by Soullivaneuh** [comment]
@Olineuve You should add this notification on a Changelog file. This is BC break and broke all applications that was using `v1.0.*`.

Btw, a BC break functionnality always should be on a new major version (e.g. `2.0`) instead of minor, according to semver rfc.

Regards.

**Comment by Soullivaneuh** [comment]
Or, at least, this `production` parameter should be required. No value should throw error so we can see immediately what is wrong after the upgrade.
