### ISSUE TITLE
Support for Paybox Direct (plus)

### ISSUE THREAD

**Issue by LouTerrailloune** [lexik/LexikPayboxBundle#37]
Anyone interested with the creation of a new service to handle this service ?

**Comment by Olineuve** [comment]
Ok, it's a bit late... but I added Direct Plus support on v1.1.0
I haven't added all the documentation yet, but your can choose your transport class. I made a transport class that uses Buzz.

# config.yml
lexik_paybox:
    ...
    transport: Lexik\Bundle\PayboxBundle\Transport\BuzzTransport

**Comment by Soullivaneuh** [comment]
@Olineuve maybe can you share some code samples for usage in addition of the configuration?
