### ISSUE TITLE
Invalid DATEQ format in ParameterResolver.php for Paybox Direct Plus

### ISSUE THREAD

**Issue by Jibato** [lexik/LexikPayboxBundle#47]
Hi,
I think there is a problem in the DirectPlus ParameterResolver format definition for the 'DATEQ' parameter.
It is '%014d' and IMHO it should be '%014s'. Because 14 digits number is too long to be an integer.

Do you confirm ?
Thanks for this great bundle!

**Comment by cedric-g** [comment]
Hi, yes maybe it's better to format it as a string. I've updated the code.

**Comment by Jibato** [comment]
Thank you!
