### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by samoussa** [lexik/LexikPayboxBundle#55]
Hi,
Could you help me ?
Is compose.json file up to date ?
thx !

-------------------------- here my error ---------------

php composer.phar up
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v2.6.11
    - Conclusion: don't install symfony/symfony v2.6.11
    - Conclusion: don't install symfony/symfony v2.6.10
    - Conclusion: don't install symfony/symfony v2.6.9
    - Conclusion: don't install symfony/symfony v2.6.8
    - Conclusion: don't install symfony/symfony v2.6.7
    - Conclusion: don't install symfony/symfony v2.6.6
    - Conclusion: don't install symfony/symfony v2.6.5
    - Conclusion: don't install symfony/symfony v2.6.4
    - Conclusion: don't install symfony/symfony v2.6.3
    - Conclusion: don't install symfony/symfony v2.6.2
    - Conclusion: don't install symfony/symfony v2.6.1
    - lexik/paybox-bundle dev-master requires symfony/options-resolver ~2.7 -> satisfiable by symfony/options-resolver[v2.7.0, v2.7.1, v2.7.2, v2.7.3].
    - lexik/paybox-bundle dev-master requires symfony/options-resolver ~2.7 -> satisfiable by symfony/options-resolver[v2.7.0, v2.7.1, v2.7.2, v2.7.3].
    - don't install symfony/options-resolver v2.7.0|don't install symfony/symfony v2.6.0
    - don't install symfony/options-resolver v2.7.1|don't install symfony/symfony v2.6.0
    - don't install symfony/options-resolver v2.7.2|don't install symfony/symfony v2.6.0
    - don't install symfony/options-resolver v2.7.3|don't install symfony/symfony v2.6.0
    - Installation request for symfony/symfony 2.6.* -> satisfiable by symfony/symfony[v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - Installation request for lexik/paybox-bundle dev-master -> satisfiable by lexik/paybox-bundle[dev-master].

**Comment by slashfan** [comment]
Hi,

Apparently your project uses Symfony 2.6 so you must use a version 1.* of this bundle (the last tag being 1.1.0). The current master branch and 2.* tags require Symfony 2.7 minimum.

Does it help ?

**Comment by samoussa** [comment]
Yes everything is ok now !
Thanks for your help and sharing
