### ISSUE TITLE
New parameters in Paybox documentation

### ISSUE THREAD

**Issue by nicosomb** [lexik/LexikPayboxBundle#62]
Hi there!

In Paybox documentation, you can use these parameters "PBX_2MONT", "PBX_DELAIS", "PBX_FREQ", "PBX_NBPAIE", "PBX_QUAND" for subscription. 

Is that planned to implement them in your bundle or do I need to fork your bundle? 

Regards, 
Nicolas

**Comment by cedric-g** [comment]
Hi, nothing planned on our side.
