### ISSUE TITLE
Credit Agricole

### ISSUE THREAD

**Issue by JulienItard** [lexik/LexikPayboxBundle#71]
Bonjour,

j'ai vu que le service E-transaction du Crédit Agricole est basé sur PayBox. Je peux utiliser ce bundle ?

merci

**Comment by Mattabile** [comment]
Oui, il faut adapter 2 choses:
l'url d'appel https://preprod-tpeweb.e-transactions.fr/php/ dans RequestTest.php , enre parametrant le setUp()
Modifier la configuration avec 'SHA512' au lieu de 'sha512' dans Configuration.php
Ne pas utiliser Curl via getWebPage() dans getServeur() de AbstractRequest.php cad modifier
/*     $doc->loadHTML($this->getWebPage(sprintf(
                '%s://%s%s',
                $server['protocol'],
                $server['host'],
                $server['test_path']
            )));*/
            $doc->loadHTMLFile($server['protocol'].'://'.$server['host'].'/'.$server['test_path']); 

C'est un très bon Bundle

**Comment by JulienItard** [comment]
Merci de ta réponse. Je ne trouve pas le fichier RequestTest.php

Merci
Julien

**Comment by Mattabile** [comment]
vendor\lexik\paybox-bundle\Tests\Paybox\System\Base\RequestTest.php
vendor\lexik\paybox-bundle\Tests\Paybox\System\Cancellation\RequestTest.php
Tester en preprod
'preprod' => array(
                    'protocol'    => 'https',
                    'host'        => '# preprod-tpeweb.e-transactions.fr',
                    'system_path' => # '/php',
                    'cancellation_path' => '/cgi-bin/ResAbon.cgi',
                    'test_path'   => # '/',
                ),

**Comment by xorgxx** [comment]
Hi 
there is not a better way to include in ```AbstractRequest.php``` the change ?
```
/* $doc->loadHTML($this->getWebPage(sprintf(
'%s://%s%s',
$server['protocol'],
$server['host'],
$server['test_path']
)));*/
$doc->loadHTMLFile($server['protocol'].'://'.$server['host'].'/'.$server['test_path']); 
```

**Comment by benoitproxi** [comment]
Salut, tu t'en es sorti avec l'utilisation de ce bundle pour le CA ? Tu as procédé à quelles modifications au final ?

Pour ma part, en modifiant les informations citées ci dessus, en preprod j'ai "No server available." sur le callAction et en prod, j'ai "Problème d'identification du commerce.
Accès refusé !" sur tpeweb.paybox.com

**Comment by JulienItard** [comment]
@benoitproxi Projet annulé, pas pu tester.
