### ISSUE TITLE
BUG url absolute symfony 3

### ISSUE THREAD

**Issue by MWJordanP** [lexik/LexikPayboxBundle#80]
We've detected an error in your SampleController.php

'PBX_EFFECTUE'     => $this->generateUrl('lexik_paybox_sample_return', array('status' => 'success'), true),

Or in symfony3 generate url use a constant and not "true or false"

'PBX_EFFECTUE'     => $this->generateUrl('lexik_paybox_sample_return', array('status' => 'success'), UrlGeneratorInterface::ABSOLUTE_URL),

Thanks by advance

**Comment by SarramegnaG** [comment]
Fixed in https://github.com/lexik/LexikPayboxBundle/pull/88

**Comment by acidjames** [comment]
@MWJordanP thanks, you need to update via composer
