### ISSUE TITLE
Monetico (credit mutuel)

### ISSUE THREAD

**Issue by xorgxx** [lexik/LexikPayboxBundle#81]
Hi i use - lexik_paybox - in same projet credit agricole, but this time i need to setup payment system for monetico (credit mutuel). i have look in the doc monetico : my question is lexik_paybox is compatible with monetico ?

thank

**Comment by acidjames** [comment]
Hi,
Monetico is another system so i would say no.

**Comment by proximiteclient** [comment]
Salut @acidjames je suis dans le même cas que toi, je cherche un moyen d'utiliser Monetico dans un projet. As tu une solution depuis ?

**Comment by proximiteclient** [comment]
Salut @xorgxx  je suis dans le même cas que toi, je cherche un moyen d'utiliser Monetico dans un projet. As tu une solution depuis ?

**Comment by xorgxx** [comment]
Yep, it work for me. [https://github.com/rollincode/RCPaiementCMCICBundle](url)

**Comment by acidjames** [comment]
Thanks guys for your input, i will now close this issue
