### ISSUE TITLE
Last commit not present & lib-curl version problem

### ISSUE THREAD

**Issue by clem983** [lexik/LexikPayboxBundle#92]
Hi, 

I have some questions about PayboxBundle.

In my local machine, I required it with composer : composer require lexik/paybox-bundle. My composer.json file contains this line : "lexik/paybox-bundle": "^2.1". But in my vendors, the file Resources/views/Macro/paybox.html.twig has an old version. The commit 4db3c56 (Fix support for Twig 2.*) seems not to be considered, and I doesn't understand how it is possible ! :)

And I have a second problem : when I try to release my project to production (Ubuntu 16.04 on a VPS), and 'composer update', I have this error : lexik/paybox-bundle v2.1.1 requires lib-curl >=7.10.0 -> the requested linked library curl has the wrong version installed or is missing from your system, make sure to have the extension providing it.
But the command 'curl -V' returns : curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
It seems the installed version is >=7.10.0, so I don't unerstand either ...

Could someone help me ? :)
Thanks a lot !

**Comment by acidjames** [comment]
Hi @clem983 

unfortunately, for the moment, you need to specify "dev-master" as your composer version, not 2.1

I don't know about the ubuntu libcurl version, i've also got 16.04 and it works as expected

maybe you can try again with "dev-master" as i hinted above

**Comment by clem983** [comment]
Thank you for your answer, @acidjames !
It works 👍 
For the curl problem, I installed php7.0-curl, I don't really understand why, but it also works !

I have just an other question : do you know when the PR of Sarramegna (configure bundle to use two accounts) will be added to the project ?

Thanks a lot :)

**Comment by acidjames** [comment]
@clem983 multiple accounts will be assessed probably after march 2018 as i'm currently under heavy load at work, please be patient, it will be merged once i find some time to study the PR ;)
