### ISSUE TITLE
Warning: DOMDocument::loadHTML(): Empty string supplied as input

### ISSUE THREAD

**Issue by rsoufir** [lexik/LexikPayboxBundle#93]
Hi there ! 

I can not call the paybox payment page with LexikPayboxBundle.

Here is the error message: "Warning: DOMDocument :: loadHTML (): Empty string supplied as input".

Here is my configuration:

**In config.yml** 

lexik_paybox:
    parameters:
        production: false
        site: 'XXXXXXX'
        rank: 'XXX'
        login: 'XXXXXXXXX'
        currencies: 
            - '978'  # EUR
        hmac:
             algorithm:      sha512  
             key: 'XXX...XXX'
             signature_name: Sign  

**In my Controller php** : 

        $paybox = $this->get('lexik_paybox.request_handler');
	$paybox->setParameters(array(
		'PBX_CMD'          => 'CMD'.time(),
		'PBX_DEVISE'       => '978',
		'PBX_PORTEUR'      => 'test@paybox.com',
		'PBX_RETOUR'       => 'Mt:M;Ref:R;Auto:A;Erreur:E',
		'PBX_TOTAL'        => '1000',
		'PBX_TYPEPAIEMENT' => 'CARTE',
		'PBX_TYPECARTE'    => 'CB',
		'PBX_EFFECTUE'     => $this->generateUrl('paiementstatus', array('status' => 'success'), true),
                'PBX_REFUSE'       => $this->generateUrl('paiementstatus', array('status' => 'denied'), true),
                'PBX_ANNULE'       => $this->generateUrl('paiementstatus', array('status' => 'canceled'), true),
	        'PBX_RUF1'         => 'POST',
		'PBX_REPONDRE_A'   => $this->generateUrl('lexik_paybox_ipn', array('time' => time()), true),
		));
		return $this->render(
			'LexikPayboxBundle:Sample:index.html.twig',
			array(
				'url'  => $paybox->getUrl(),
				'form' => $paybox->getForm()->createView(),
			)
		);

You can see my error in the screenshot in attach files.

Thank you in advance for your help !

![error_paybox](https://user-images.githubusercontent.com/32511526/33932610-acb44c22-dff3-11e7-9e5f-3fb8d7c5c966.PNG)

**Comment by acidjames** [comment]
@rsoufir can you try to test the routes "paiementstatus" in another context, like just making a link to them using twig ?

i've never seen this error, but it looks like some route generation error

**Comment by ftila** [comment]
le problème au libcurl:
lancer la commande curl coté serveur si vous obtenez les mêmes resultats alors exécuter les commandes qui suivent=>

- curl https://tpeweb.paybox.com/load.html
	curl: /usr/local/lib/libcurl.so.4: no version information available (required by curl)
	curl: (48) An unknown option was passed in to libcurl

-  locate libcurl.so.4
	/opt/hp/hpsmh/lib/libcurl.so.4
	/opt/hp/hpsmh/lib/libcurl.so.4.3.0
	/root/curl/curl-7.52.1/lib/.libs/libcurl.so.4
	/root/curl/curl-7.52.1/lib/.libs/libcurl.so.4.4.0
	/root/curl1/curl-7.58.0/lib/.libs/libcurl.so.4
	/root/curl1/curl-7.58.0/lib/.libs/libcurl.so.4.5.0
	/root/curl_git/lib/.libs/libcurl.so.4
	/root/curl_git/lib/.libs/libcurl.so.4.5.0
	/usr/lib/x86_64-linux-gnu/libcurl.so.4
	/usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0
	/usr/local/lib/libcurl.so.4
	/usr/local/lib/libcurl.so.4.4.0

- ls -l /usr/local/lib/libcurl.so.4
	lrwxrwxrwx 1 root root 16 Dec 17 10:32 /usr/local/lib/libcurl.so.4 -> libcurl.so.4.4.0

- sudo mv /usr/local/lib/libcurl.so.4 /usr/local/lib/libcurl.so.4.bck

- sudo ln -s /usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0 /usr/local/lib/libcurl.so.4
	libcurl.so.4.3.0

- sudo ln -s /usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0 /usr/local/lib/libcurl.so.4

- ls -l /usr/local/lib/libcurl.so.4
	lrwxrwxrwx 1 root root 42 Dec 21 12:12 /usr/local/lib/libcurl.so.4 -> /usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0

- cmake -version
	cmake version 2.8.12.2

- curl https://tpeweb.paybox.com/load.html

```

	<!DOCTYPE html>
	<html>
	<head>
			<title>Server status</title>
	</head>
	<body>
			<div><center>
			<table BORDER="0" WIDTH="100%" HEIGHT="95%">
			<tr><td align="center">
					<font type="arial"><b>T</b>peweb.<b>P</b>aybox.<b>C</b>om</font><font color="white"> - 24</font>
			</td></tr>
			</table>
			</center></div>
			<div id="server_status" style="text-align:center;">OK</div>
	</body>
	</html>

```

- /etc/init.d/apache2 restart

**Comment by alexandreb09** [comment]
I'm getting the same issue and simply fix it by removing the checks. 

The error is raised after calling [getWebPage](https://github.com/lexik/LexikPayboxBundle/blob/ffa35cc2753e69d8b3151aecc5e5b9199fd9c2ac/Paybox/AbstractRequest.php#L170) on `https://preprod-tpeweb.paybox.com/load.html` which is returning an empty string.

One simple solution is to remove this call to get the server URL. The server URL are available on the [doc](http://www1.paybox.com/espace-integrateur-documentation/la-plateforme-de-tests/). 

For example, for a *pre-prod* test, you can use:
```
// Server URL
$PAYBOX_DOMAIN_SERVER = "preprod-tpeweb.paybox.com";
$paybox_url = "https://".$PAYBOX_DOMAIN_SERVER."/cgi/MYchoix_pagepaiement.cgi";
```

The controller becomes:
```
public function callAction(){

        // Server URL
        $PAYBOX_DOMAIN_SERVER = "preprod-tpeweb.paybox.com";
        $paybox_url = "https://".$PAYBOX_DOMAIN_SERVER."/cgi/MYchoix_pagepaiement.cgi";

        $paybox = $this->get('lexik_paybox.request_handler');
        $paybox->setParameters(array(
            'PBX_SITE'          => "1999888",
            'PBX_RANG'          => "32",
            'PBX_IDENTIFIANT'   => "110647233",
            'PBX_TOTAL'         => "999",
            'PBX_DEVISE'        => "978",
            'PBX_CMD'           => "TEST Paybox".mktime(),
            'PBX_PORTEUR'       => "test@paybox.com",
            'PBX_RETOUR'        => "Mt:M;Ref:R;Auto:A;Erreur:E",
            'PBX_HASH'          => "SHA512",

//            'PBX_TYPEPAIEMENT' => 'CARTE',
//            'PBX_TYPECARTE'    => 'CB',

            'PBX_EFFECTUE'     => $this->generateUrl('lexik_paybox_sample_return', array('status' => 'success'), UrlGeneratorInterface::ABSOLUTE_URL),
            'PBX_REFUSE'       => $this->generateUrl('lexik_paybox_sample_return', array('status' => 'denied'), UrlGeneratorInterface::ABSOLUTE_URL),
            'PBX_ANNULE'       => $this->generateUrl('lexik_paybox_sample_return', array('status' => 'canceled'), UrlGeneratorInterface::ABSOLUTE_URL),
            'PBX_RUF1'         => 'POST',
            'PBX_REPONDRE_A'   => $this->generateUrl('lexik_paybox_ipn', array('time' => time()), UrlGeneratorInterface::ABSOLUTE_URL),
        ));

        return $this->render(
            'LexikPayboxBundle:Sample:index.html.twig',
            array(
                'url'  => $paybox_url, //$paybox->getUrl(),
                'form' => $paybox->getForm()->createView(),
            )
        );
}
```
I have openned a discussion on [StackOverflow](https://stackoverflow.com/questions/57227458/lexik-paybox-installation-warning-domdocumentloadhtml-empty-string-suppli) with my files detail.

There should have *better* solution but works for the moment.
