### ISSUE TITLE
3D-Secure v2 integration

### ISSUE THREAD

**Issue by lucuhb** [lexik/LexikPayboxBundle#97]
To comply the 3D-Secure v2 , Paybox added 2 new variables to send : 

- PBX_SHOPPINGCART, in xml :  

```
<?xml version="1.0" encoding="utf-8"?>
<shoppingcart>
 <total>
 <totalQuantity>15</totalQuantity>
 </total>
</shoppingcart>
```

- PBX_BILLING, in xml : 

```
<?xml version="1.0" encoding="utf-8"?>
<Billing>
 <Address>
 <FirstName>Jean</FirstName>
 <LastName>Dupont</LastName>
 <Address1>12 rue Paul Dautier</Address1>
 <ZipCode>78140</ZipCode>
 <City>Vélizy-Villacoublay</City>
 <CountryCode>250</CountryCode>
 </Address>
</Billing>

```
Is it possible to add these two new variables ?
Thanks

**Comment by acidjames** [comment]
@lucuhb sorry, this project isn't maintained anymore

**Comment by Astro-Otter-Space** [comment]
Sorry for reup this topic, I need to add this feature also. If i'm forking the repo and apply https://github.com/lexik/LexikPayboxBundle/pull/98/files , does it enough?

**Comment by acidjames** [comment]
Bonjour @HamHamFonFon 

Tu pourrais pull le répo suivant : https://github.com/EnMarche/LexikPayboxBundle

Ils ont l'air de continuer à le maintenir de leur côté.

bon courage à toi,

**Comment by Astro-Otter-Space** [comment]
J'ai récupéré le repo, mis dans le gitlab de mon entreprise et fait du cherry-pick des corrections dont j'ai besoin 👍
